package com.yusufteker.planora.core.export

import com.yusufteker.planora.shared.api.ItemDetails
import com.yusufteker.planora.shared.api.TaskDto
import com.yusufteker.planora.shared.api.TaskStatus

/**
 * Format options for task data export.
 */
enum class ExportFormat {
    CSV,
    REPORT
}

/**
 * Platform-specific data exporter for tasks.
 *
 * Generates CSV or formatted report files from the provided task list and triggers
 * the native share sheet (Android Intent / iOS UIActivityViewController) so the user
 * can save or send the file.
 */
expect class TaskCsvExporter() {

    /**
     * Builds an export representation of [tasks] and opens the platform share sheet.
     *
     * @param tasks Tasks to include in the export.
     * @param fileName Suggested file name shown in the share sheet (e.g. "planora_tasks").
     * @param format The desired export format (CSV or Formatted Report).
     * @return True if the export was initiated successfully, false otherwise.
     */
    fun export(tasks: List<TaskDto>, fileName: String, format: ExportFormat = ExportFormat.CSV): Boolean
}

/**
 * Converts a list of [TaskDto] objects into a CSV-formatted string.
 *
 * The first line is a header row with column names.
 * Each subsequent line represents one task, with values escaped for CSV safety.
 *
 * @return A UTF-8 CSV string ready to be written to a file or shared.
 */
fun List<TaskDto>.toCsvString(): String {
    val header = listOf(
        "Title", "Description", "Status", "Priority", "Type",
        "Start Time", "End Time", "Is Recurring", "Tags", "Is Pinned"
    ).joinToString(",")

    val rows = map { task ->
        val priority = (task.specificDetails as? ItemDetails.Task)?.priority?.name ?: "MEDIUM"
        listOf(
            task.title.escapeCsv(),
            task.description?.escapeCsv() ?: "",
            task.status.name,
            priority,
            task.type.name,
            task.startTime.toString(),
            task.endTime?.toString() ?: "",
            task.isRecurring.toString(),
            task.tags.joinToString(";").escapeCsv(),
            task.isPinned.toString()
        ).joinToString(",")
    }

    return (listOf(header) + rows).joinToString("\n")
}

/**
 * Converts a list of [TaskDto] objects into a clean, human-readable summary report.
 */
fun List<TaskDto>.toReportString(): String {
    val completedCount = count { it.status == TaskStatus.COMPLETED || it.status.name == "DONE" }
    val pendingCount = size - completedCount

    val sb = StringBuilder()
    sb.appendLine("================================================")
    sb.appendLine("             PLANORA TASK & PLAN REPORT         ")
    sb.appendLine("================================================")
    sb.appendLine("Total Tasks: $size")
    sb.appendLine("Completed: $completedCount")
    sb.appendLine("Pending/In-Progress: $pendingCount")
    sb.appendLine("------------------------------------------------\n")

    forEachIndexed { index, task ->
        val isCompleted = task.status == TaskStatus.COMPLETED || task.status.name == "DONE"
        val statusSymbol = if (isCompleted) "[✓]" else "[ ]"
        val priority = (task.specificDetails as? ItemDetails.Task)?.priority?.name ?: "MEDIUM"

        sb.appendLine("${index + 1}. $statusSymbol ${task.title}")
        if (!task.description.isNullOrBlank()) {
            sb.appendLine("   Details: ${task.description}")
        }
        sb.appendLine("   Status: ${task.status.name} | Priority: $priority | Type: ${task.type.name}")
        if (task.startTime > 0) {
            sb.appendLine("   Start Time: ${task.startTime}")
        }
        if (task.endTime != null && task.endTime!! > 0) {
            sb.appendLine("   End Time: ${task.endTime}")
        }
        if (task.tags.isNotEmpty()) {
            sb.appendLine("   Tags: #${task.tags.joinToString(" #")}")
        }
        sb.appendLine()
    }

    sb.appendLine("================================================")
    sb.appendLine("Generated by Planora")
    return sb.toString()
}

/** Wraps a string in double-quotes and escapes internal double-quotes for CSV safety. */
private fun String.escapeCsv(): String {
    return if (contains(",") || contains("\"") || contains("\n")) {
        "\"${replace("\"", "\"\"")}\""
    } else {
        this
    }
}
