ALTER TABLE plan_rooms ALTER COLUMN id TYPE VARCHAR(100);
ALTER TABLE plan_room_members ALTER COLUMN room_id TYPE VARCHAR(100);
ALTER TABLE tasks ALTER COLUMN id TYPE VARCHAR(100);
ALTER TABLE tasks ALTER COLUMN parent_id TYPE VARCHAR(100);
ALTER TABLE task_shared_rooms ALTER COLUMN task_id TYPE VARCHAR(100);
ALTER TABLE task_shared_rooms ALTER COLUMN room_id TYPE VARCHAR(100);
