package com.yusufteker.planora.server.integration

import com.yusufteker.planora.server.database.DatabaseFactory.dbQuery
import com.yusufteker.planora.server.database.tables.UserEntity
import com.yusufteker.planora.server.database.tables.UsersTable
import com.yusufteker.planora.server.security.HashingService
import com.yusufteker.planora.server.support.BaseDatabaseIntegrationTest
import org.jetbrains.exposed.sql.selectAll
import org.jetbrains.exposed.sql.transactions.transaction
import java.time.Instant
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Real PostgreSQL integration tests validating Flyway migration, database operations,
 * and test isolation using Testcontainers.
 */
class DatabaseIntegrationTest : BaseDatabaseIntegrationTest() {

    /**
     * Verifies that Flyway migrations ran and the users table exists and is initially empty.
     */
    @Test
    fun databaseShouldBeInitializedAndMigratedWithEmptyTables() {
        val initialUserCount = transaction {
            UsersTable.selectAll().count()
        }
        assertEquals(0L, initialUserCount, "Database tables must be cleanly wiped by test isolation setup")
    }

    /**
     * Verifies inserting and querying user records in the real PostgreSQL container.
     */
    @Test
    fun shouldPersistAndRetrieveUserInPostgres() {
        val email = "integration_test@planora.com"
        val username = "integration_user"

        val createdUserId = transaction {
            val user = UserEntity.new {
                this.name = "Integration Test User"
                this.username = username
                this.email = email
                this.passwordHash = HashingService.hashPassword("SecurePassword123!")
                this.createdAt = Instant.now()
            }
            user.id.value
        }

        assertTrue(createdUserId > 0, "User ID should be generated by PostgreSQL serial/identity")

        val fetchedUser = transaction {
            UserEntity.findById(createdUserId)
        }

        assertNotNull(fetchedUser)
        assertEquals(email, fetchedUser.email)
        assertEquals(username, fetchedUser.username)
    }

    /**
     * Verifies test isolation: previous test insertions must not leak into subsequent tests.
     */
    @Test
    fun shouldVerifyTestIsolationBetweenConsecutiveTests() {
        // Because @Before cleanDatabase() runs before every test, count must be 0
        val count = transaction {
            UsersTable.selectAll().count()
        }
        assertEquals(0L, count, "Previous test data must be cleaned up to guarantee test isolation")
    }
}
